#!/usr/bin/env node

// replace .git/hooks/pre-commit hook by these lines
//
// will run `npm test` and prevent commits on test fail
// or .git/hooks/post-commit, .git/hooks/pre-commit, .git/hooks/post-receive, ...
//
// To enable this hook, make this file executable by `chmod +x .git/hooks/pre-commit`.
//
// http://progit.org/book/ch7-3.html


var npm = nrequire('npm');
if (npm) return npm.load(function(e, n) {
  this.commands.test(function(e) {
    process.exit(e ? 1 : 0);
  });
});


// npm not installed locally, spawn process instead.
// Basically the same, but less pretty.
var spawn = require('child_process').spawn,
  ch = spawn('npm', ['test']);

ch.stdout.pipe(process.stdout, {end: false});
ch.stderr.pipe(process.stderr);
ch.on('exit', function (code) {
  process.exit(code ? 1 : 0);
});


function nrequire(m) {
  var n;
  try { n = require(m); }
  catch(e) { console.log('please, install ' + m + ' locally to be able to use it programmatically. Will spawn process instead. \n'); }
  return n;
}

