.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODE\-TTY" "3" "October 2011" "" ""
.
.SH "NAME"
\fBnode-tty\fR \-\- http://nodejs\.org/docs/v0\.4\.8/api/tty\.html
.
.SH "TTY"
Use \fBrequire(\'tty\')\fR to access this module\.
.
.P
Example:
.
.IP "" 4
.
.nf
var tty = require(\'tty\');
tty\.setRawMode(true);
process\.stdin\.resume();
process\.stdin\.on(\'keypress\', function(char, key) {
  if (key && key\.ctrl && key\.name == \'c\') {
    console\.log(\'graceful exit\');
    process\.exit()
  }
});
.
.fi
.
.IP "" 0
.
.SS "tty\.open(path, args=[])"
Spawns a new process with the executable pointed to by \fBpath\fR as the session
leader to a new pseudo terminal\.
.
.P
Returns an array \fB[slaveFD, childProcess]\fR\|\. \fBslaveFD\fR is the file descriptor
of the slave end of the pseudo terminal\. \fBchildProcess\fR is a child process
object\.
.
.SS "tty\.isatty(fd)"
Returns \fBtrue\fR or \fBfalse\fR depending on if the \fBfd\fR is associated with a
terminal\.
.
.SS "tty\.setRawMode(mode)"
\fBmode\fR should be \fBtrue\fR or \fBfalse\fR\|\. This sets the properties of the current
process\'s stdin fd to act either as a raw device or default\.
.
.SS "tty\.setWindowSize(fd, row, col)"
\fBioctl\fRs the window size settings to the file descriptor\.
.
.SS "tty\.getWindowSize(fd)"
Returns \fB[row, col]\fR for the TTY associated with the file descriptor\.