.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODE\-NET" "3" "October 2011" "" ""
.
.SH "NAME"
\fBnode-net\fR \-\- http://nodejs\.org/docs/v0\.4\.8/api/net\.html
.
.SH "net"
The \fBnet\fR module provides you with an asynchronous network wrapper\. It contains
methods for creating both servers and clients (called streams)\. You can include
this module with \fBrequire("net");\fR
.
.SS "net\.createServer([options], [connectionListener])"
Creates a new TCP server\. The \fBconnectionListener\fR argument is
automatically set as a listener for the \fB\'connection\'\fR event\.
.
.P
\fBoptions\fR is an object with the following defaults:
.
.IP "" 4
.
.nf
{ allowHalfOpen: false
}
.
.fi
.
.IP "" 0
.
.P
If \fBallowHalfOpen\fR is \fBtrue\fR, then the socket won\'t automatically send FIN
packet when the other end of the socket sends a FIN packet\. The socket becomes
non\-readable, but still writable\. You should call the end() method explicitly\.
See \fB\'end\'\fR event for more information\.
.
.SS "net\.createConnection(arguments\.\.\.)"
Construct a new socket object and opens a socket to the given location\. When
the socket is established the \fB\'connect\'\fR event will be emitted\.
.
.P
The arguments for this method change the type of connection:
.
.IP "\(bu" 4
\fBnet\.createConnection(port, [host], [callback])\fR
.
.IP
Creates a TCP connection to \fBport\fR on \fBhost\fR\|\. If \fBhost\fR is omitted, \fBlocalhost\fR will be assumed\.
.
.IP "\(bu" 4
\fBnet\.createConnection(path, [callback])\fR
.
.IP
Creates unix socket connection to \fBpath\fR
.
.IP "" 0
.
.P
The \fBcallback\fR parameter will be added as an listener for the \'connect` event\.
.
.HR
.
.SS "net\.Server"
This class is used to create a TCP or UNIX server\.
.
.P
Here is an example of a echo server which listens for connections
on port 8124:
.
.IP "" 4
.
.nf
var net = require(\'net\');
var server = net\.createServer(function (c) {
  c\.write(\'hello\\r\\n\');
  c\.pipe(c);
});
server\.listen(8124, \'localhost\');
.
.fi
.
.IP "" 0
.
.P
Test this by using \fBtelnet\fR:
.
.IP "" 4
.
.nf
telnet localhost 8124
.
.fi
.
.IP "" 0
.
.P
To listen on the socket \fB/tmp/echo\.sock\fR the last line would just be
changed to
.
.IP "" 4
.
.nf
server\.listen(\'/tmp/echo\.sock\');
.
.fi
.
.IP "" 0
.
.P
Use \fBnc\fR to connect to a UNIX domain socket server:
.
.IP "" 4
.
.nf
nc \-U /tmp/echo\.sock
.
.fi
.
.IP "" 0
.
.P
\fBnet\.Server\fR is an \fBEventEmitter\fR with the following events:
.
.TP
server\.listen(port, [host], [callback])
.Begin accepting connections on the specified \fBport\fR and \fBhost\fR\|\.  If the \fBhost\fR is omitted, the server will accept connections directed to any
IPv4 address (\fBINADDR_ANY\fR)\.
.
.P
This function is asynchronous\. The last parameter \fBcallback\fR will be called
when the server has been bound\.
.
.P
One issue some users run into is getting \fBEADDRINUSE\fR errors\. Meaning
another server is already running on the requested port\. One way of handling this
would be to wait a second and the try again\. This can be done with
.
.IP "" 4
.
.nf
server\.on(\'error\', function (e) {
  if (e\.code == \'EADDRINUSE\') {
    console\.log(\'Address in use, retrying\.\.\.\');
    setTimeout(function () {
      server\.close();
      server\.listen(PORT, HOST);
    }, 1000);
  }
});
.
.fi
.
.IP "" 0
.
.P
(Note: All sockets in Node are set SO_REUSEADDR already)
.
.TP
server\.listen(path, [callback])
.Start a UNIX socket server listening for connections on the given \fBpath\fR\|\.
.
.P
This function is asynchronous\. The last parameter \fBcallback\fR will be called
when the server has been bound\.
.
.TP
server\.listenFD(fd)
.Start a server listening for connections on the given file descriptor\.
.
.P
This file descriptor must have already had the \fBbind(2)\fR and \fBlisten(2)\fR system
calls invoked on it\.  Additionally, it must be set non\-blocking; try \fBfcntl(fd, F_SETFL, O_NONBLOCK)\fR\|\.
.
.TP
server\.pause(msecs)
.Stop accepting connections for the given number of milliseconds (default is
one second)\.  This could be useful for throttling new connections against
DoS attacks or other oversubscription\.
.
.TP
server\.close()
.Stops the server from accepting new connections\. This function is
asynchronous, the server is finally closed when the server emits a \fB\'close\'\fR
event\.
.
.TP
server\.address()
.Returns the bound address and port of the server as reported by the operating system\.
Useful to find which port was assigned when giving getting an OS\-assigned address\.
Returns an object with two properties, e\.g\. \fB{"address":"127\.0\.0\.1", "port":2121}\fR
.
.P
Example:
.
.IP "" 4
.
.nf
var server = net\.createServer(function (socket) {
  socket\.end("goodbye\\n");
});
// grab a random port\.
server\.listen(function() {
  address = server\.address();
  console\.log("opened server on %j", address);
});
.
.fi
.
.IP "" 0
.
.TP
server\.maxConnections
.Set this property to reject connections when the server\'s connection count gets high\.
.
.TP
server\.connections
.The number of concurrent connections on the server\.
.
.TP
Event: \'connection\'
.\fBfunction (socket) {}\fR
.
.P
Emitted when a new connection is made\. \fBsocket\fR is an instance of \fBnet\.Socket\fR\|\.
.
.TP
Event: \'close\'
.\fBfunction () {}\fR
.
.P
Emitted when the server closes\.
.
.HR
.
.SS "net\.Socket"
This object is an abstraction of of a TCP or UNIX socket\.  \fBnet\.Socket\fR
instances implement a duplex Stream interface\.  They can be created by the
user and used as a client (with \fBconnect()\fR) or they can be created by Node
and passed to the user through the \fB\'connection\'\fR event of a server\.
.
.P
\fBnet\.Socket\fR instances are EventEmitters with the following events:
.
.TP
new net\.Socket([options])
.Construct a new socket object\.
.
.P
\fBoptions\fR is an object with the following defaults:
.
.IP "" 4
.
.nf
{ fd: null
  type: null
  allowHalfOpen: false
}
.
.fi
.
.IP "" 0
.
.P
\fBfd\fR allows you to specify the existing file descriptor of socket\. \fBtype\fR
specified underlying protocol\. It can be \fB\'tcp4\'\fR, \fB\'tcp6\'\fR, or \fB\'unix\'\fR\|\.
About \fBallowHalfOpen\fR, refer to \fBcreateServer()\fR and \fB\'end\'\fR event\.
.
.TP
socket\.connect(port, [host], [callback])
.
.TP
socket\.connect(path, [callback])
.Opens the connection for a given socket\. If \fBport\fR and \fBhost\fR are given,
then the socket will be opened as a TCP socket, if \fBhost\fR is omitted, \fBlocalhost\fR will be assumed\. If a \fBpath\fR is given, the socket will be
opened as a unix socket to that path\.
.
.P
Normally this method is not needed, as \fBnet\.createConnection\fR opens the
socket\. Use this only if you are implementing a custom Socket or if a
Socket is closed and you want to reuse it to connect to another server\.
.
.P
This function is asynchronous\. When the \fB\'connect\'\fR event is emitted the
socket is established\. If there is a problem connecting, the \fB\'connect\'\fR
event will not be emitted, the \fB\'error\'\fR event will be emitted with
the exception\.
.
.P
The \fBcallback\fR parameter will be added as an listener for the \'connect\'
event\.
.
.TP
socket\.bufferSize
.\fBnet\.Socket\fR has the property that \fBsocket\.write()\fR always works\. This is to
help users get up an running quickly\. The computer cannot necessarily keep up
with the amount of data that is written to a socket \- the network connection simply
might be too slow\. Node will internally queue up the data written to a socket and
send it out over the wire when it is possible\. (Internally it is polling on
the socket\'s file descriptor for being writable)\.
.
.P
The consequence of this internal buffering is that memory may grow\. This
property shows the number of characters currently buffered to be written\.
(Number of characters is approximately equal to the number of bytes to be
written, but the buffer may contain strings, and the strings are lazily
encoded, so the exact number of bytes is not known\.)
.
.P
Users who experience large or growing \fBbufferSize\fR should attempt to
"throttle" the data flows in their program with \fBpause()\fR and resume()`\.
.
.TP
socket\.setEncoding(encoding=null)
.Sets the encoding (either \fB\'ascii\'\fR, \fB\'utf8\'\fR, or \fB\'base64\'\fR) for data that is
received\.
.
.TP
socket\.setSecure()
.This function has been removed in v0\.3\. It used to upgrade the connection to
SSL/TLS\. See the TLS section \fItls\.html#tLS_\fR for the new API\.
.
.TP
socket\.write(data, [encoding], [callback])
.Sends data on the socket\. The second parameter specifies the encoding in the
case of a string\-\-it defaults to UTF8 encoding\.
.
.P
Returns \fBtrue\fR if the entire data was flushed successfully to the kernel
buffer\. Returns \fBfalse\fR if all or part of the data was queued in user memory\. \fB\'drain\'\fR will be emitted when the buffer is again free\.
.
.P
The optional \fBcallback\fR parameter will be executed when the data is finally
written out \- this may not be immediately\.
.
.TP
socket\.write(data, [encoding], [fileDescriptor], [callback])
.For UNIX sockets, it is possible to send a file descriptor through the
socket\. Simply add the \fBfileDescriptor\fR argument and listen for the \fB\'fd\'\fR
event on the other end\.
.
.TP
socket\.end([data], [encoding])
.Half\-closes the socket\. I\.E\., it sends a FIN packet\. It is possible the
server will still send some data\.
.
.P
If \fBdata\fR is specified, it is equivalent to calling \fBsocket\.write(data, encoding)\fR
followed by \fBsocket\.end()\fR\|\.
.
.TP
socket\.destroy()
.Ensures that no more I/O activity happens on this socket\. Only necessary in
case of errors (parse error or so)\.
.
.TP
socket\.pause()
.Pauses the reading of data\. That is, \fB\'data\'\fR events will not be emitted\.
Useful to throttle back an upload\.
.
.TP
socket\.resume()
.Resumes reading after a call to \fBpause()\fR\|\.
.
.TP
socket\.setTimeout(timeout, [callback])
.Sets the socket to timeout after \fBtimeout\fR milliseconds of inactivity on
the socket\. By default \fBnet\.Socket\fR do not have a timeout\.
.
.P
When an idle timeout is triggered the socket will receive a \fB\'timeout\'\fR
event but the connection will not be severed\. The user must manually \fBend()\fR
or \fBdestroy()\fR the socket\.
.
.P
If \fBtimeout\fR is 0, then the existing idle timeout is disabled\.
.
.P
The optional \fBcallback\fR parameter will be added as a one time listener for the \fB\'timeout\'\fR event\.
.
.TP
socket\.setNoDelay(noDelay=true)
.Disables the Nagle algorithm\. By default TCP connections use the Nagle
algorithm, they buffer data before sending it off\. Setting \fBnoDelay\fR will
immediately fire off data each time \fBsocket\.write()\fR is called\.
.
.TP
socket\.setKeepAlive(enable=false, [initialDelay])
.Enable/disable keep\-alive functionality, and optionally set the initial
delay before the first keepalive probe is sent on an idle socket\.
Set \fBinitialDelay\fR (in milliseconds) to set the delay between the last
data packet received and the first keepalive probe\. Setting 0 for
initialDelay will leave the value unchanged from the default
(or previous) setting\.
.
.TP
socket\.address()
.Returns the bound address and port of the socket as reported by the operating system\.
Returns an object with two properties, e\.g\. \fB{"address":"192\.168\.57\.1", "port":62053}\fR
.
.TP
socket\.remoteAddress
.The string representation of the remote IP address\. For example, \fB\'74\.125\.127\.100\'\fR or \fB\'2001:4860:a005::68\'\fR\|\.
.
.TP
socket\.remotePort
.The numeric representation of the remote port\. For example, \fB80\fR or \fB21\fR\|\.
.
.TP
socket\.bytesRead
.The amount of received bytes\.
.
.TP
socket\.bytesWritten
.The amount of bytes sent\.
.
.TP
Event: \'connect\'
.\fBfunction () { }\fR
.
.P
Emitted when a socket connection successfully is established\.
See \fBconnect()\fR\|\.
.
.TP
Event: \'data\'
.\fBfunction (data) { }\fR
.
.P
Emitted when data is received\.  The argument \fBdata\fR will be a \fBBuffer\fR or \fBString\fR\|\.  Encoding of data is set by \fBsocket\.setEncoding()\fR\|\.
(See the Readable Stream \fIstreams\.html#readable_Stream\fR section for more information\.)
.
.TP
Event: \'end\'
.\fBfunction () { }\fR
.
.P
Emitted when the other end of the socket sends a FIN packet\.
.
.P
By default (\fBallowHalfOpen == false\fR) the socket will destroy its file
descriptor  once it has written out its pending write queue\.  However, by
setting \fBallowHalfOpen == true\fR the socket will not automatically \fBend()\fR
its side allowing the user to write arbitrary amounts of data, with the
caveat that the user is required to \fBend()\fR their side now\.
.
.TP
Event: \'timeout\'
.\fBfunction () { }\fR
.
.P
Emitted if the socket times out from inactivity\. This is only to notify that
the socket has been idle\. The user must manually close the connection\.
.
.P
See also: \fBsocket\.setTimeout()\fR
.
.TP
Event: \'drain\'
.\fBfunction () { }\fR
.
.P
Emitted when the write buffer becomes empty\. Can be used to throttle uploads\.
.
.TP
Event: \'error\'
.\fBfunction (exception) { }\fR
.
.P
Emitted when an error occurs\.  The \fB\'close\'\fR event will be called directly
following this event\.
.
.TP
Event: \'close\'
.\fBfunction (had_error) { }\fR
.
.P
Emitted once the socket is fully closed\. The argument \fBhad_error\fR is a boolean
which says if the socket was closed due to a transmission error\.
.
.HR
.
.SS "net\.isIP"
.
.TP
net\.isIP(input)
.Tests if input is an IP address\. Returns 0 for invalid strings,
returns 4 for IP version 4 addresses, and returns 6 for IP version 6 addresses\.
.
.TP
net\.isIPv4(input)
.Returns true if input is a version 4 IP address, otherwise returns false\.
.
.TP
net\.isIPv6(input)
.Returns true if input is a version 6 IP address, otherwise returns false\.