.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODE\-MODULES" "3" "October 2011" "" ""
.
.SH "NAME"
\fBnode-modules\fR \-\- http://nodejs\.org/docs/v0\.4\.8/api/modules\.html
.
.SH "Modules"
Node has a simple module loading system\.  In Node, files and modules are in
one\-to\-one correspondence\.  As an example, \fBfoo\.js\fR loads the module \fBcircle\.js\fR in the same directory\.
.
.P
The contents of \fBfoo\.js\fR:
.
.IP "" 4
.
.nf
var circle = require(\'\./circle\.js\');
console\.log( \'The area of a circle of radius 4 is \'
           + circle\.area(4));
.
.fi
.
.IP "" 0
.
.P
The contents of \fBcircle\.js\fR:
.
.IP "" 4
.
.nf
var PI = Math\.PI;
exports\.area = function (r) {
  return PI * r * r;
};
exports\.circumference = function (r) {
  return 2 * PI * r;
};
.
.fi
.
.IP "" 0
.
.P
The module \fBcircle\.js\fR has exported the functions \fBarea()\fR and \fBcircumference()\fR\|\.  To export an object, add to the special \fBexports\fR
object\.
.
.P
Variables
local to the module will be private\. In this example the variable \fBPI\fR is
private to \fBcircle\.js\fR\|\.
.
.SS "Core Modules"
Node has several modules compiled into the binary\.  These modules are
described in greater detail elsewhere in this documentation\.
.
.P
The core modules are defined in node\'s source in the \fBlib/\fR folder\.
.
.P
Core modules are always preferentially loaded if their identifier is
passed to \fBrequire()\fR\|\.  For instance, \fBrequire(\'http\')\fR will always
return the built in HTTP module, even if there is a file by that name\.
.
.SS "File Modules"
If the exact filename is not found, then node will attempt to load the
required filename with the added extension of \fB\|\.js\fR, and then \fB\|\.node\fR\|\.
.
.P
\fB\|\.js\fR files are interpreted as JavaScript text files, and \fB\|\.node\fR files
are interpreted as compiled addon modules loaded with \fBdlopen\fR\|\.
.
.P
A module prefixed with \fB\'/\'\fR is an absolute path to the file\.  For
example, \fBrequire(\'/home/marco/foo\.js\')\fR will load the file at \fB/home/marco/foo\.js\fR\|\.
.
.P
A module prefixed with \fB\'\./\'\fR is relative to the file calling \fBrequire()\fR\|\.
That is, \fBcircle\.js\fR must be in the same directory as \fBfoo\.js\fR for \fBrequire(\'\./circle\')\fR to find it\.
.
.P
Without a leading \'/\' or \'\./\' to indicate a file, the module is either a
"core module" or is loaded from a \fBnode_modules\fR folder\.
.
.SS "Loading from `node_modules` Folders"
If the module identifier passed to \fBrequire()\fR is not a native module,
and does not begin with \fB\'/\'\fR, \fB\'\.\./\'\fR, or \fB\'\./\'\fR, then node starts at the
parent directory of the current module, and adds \fB/node_modules\fR, and
attempts to load the module from that location\.
.
.P
If it is not found there, then it moves to the parent directory, and so
on, until the root of the tree is reached\.
.
.P
For example, if the file at \fB\'/home/ry/projects/foo\.js\'\fR called \fBrequire(\'bar\.js\')\fR, then node would look in the following locations, in
this order:
.
.IP "\(bu" 4
\fB/home/ry/projects/node_modules/bar\.js\fR
.
.IP "\(bu" 4
\fB/home/ry/node_modules/bar\.js\fR
.
.IP "\(bu" 4
\fB/home/node_modules/bar\.js\fR
.
.IP "\(bu" 4
\fB/node_modules/bar\.js\fR
.
.IP "" 0
.
.P
This allows programs to localize their dependencies, so that they do not
clash\.
.
.SS "Folders as Modules"
It is convenient to organize programs and libraries into self\-contained
directories, and then provide a single entry point to that library\.
There are three ways in which a folder may be passed to \fBrequire()\fR as
an argument\.
.
.P
The first is to create a \fBpackage\.json\fR file in the root of the folder,
which specifies a \fBmain\fR module\.  An example package\.json file might
look like this:
.
.IP "" 4
.
.nf
{ "name" : "some\-library",
  "main" : "\./lib/some\-library\.js" }
.
.fi
.
.IP "" 0
.
.P
If this was in a folder at \fB\|\./some\-library\fR, then \fBrequire(\'\./some\-library\')\fR would attempt to load \fB\|\./some\-library/lib/some\-library\.js\fR\|\.
.
.P
This is the extent of Node\'s awareness of package\.json files\.
.
.P
If there is no package\.json file present in the directory, then node
will attempt to load an \fBindex\.js\fR or \fBindex\.node\fR file out of that
directory\.  For example, if there was no package\.json file in the above
example, then \fBrequire(\'\./some\-library\')\fR would attempt to load:
.
.IP "\(bu" 4
\fB\|\./some\-library/index\.js\fR
.
.IP "\(bu" 4
\fB\|\./some\-library/index\.node\fR
.
.IP "" 0
.
.SS "Caching"
Modules are cached after the first time they are loaded\.  This means
(among other things) that every call to \fBrequire(\'foo\')\fR will get
exactly the same object returned, if it would resolve to the same file\.
.
.P
Multiple calls to \fBrequire(\'foo\')\fR may not cause the module code to be
executed multiple times\.  This is an important feature\.  With it,
"partially done" objects can be returned, thus allowing transitive
dependencies to be loaded even when they would cause cycles\.
.
.P
If you want to have a module execute code multiple times, then export a
function, and call that function\.
.
.TP
Module Caching Caveats
.Modules are cached based on their resolved filename\.  Since modules may
resolve to a different filename based on the location of the calling
module (loading from \fBnode_modules\fR folders), it is not a \fIguarantee\fR
that \fBrequire(\'foo\')\fR will always return the exact same object, if it
would resolve to different files\.
.
.SS "module\.exports"
The \fBexports\fR object is created by the Module system\. Sometimes this is not
acceptable, many want their module to be an instance of some class\. To do this
assign the desired export object to \fBmodule\.exports\fR\|\. For example suppose we
were making a module called \fBa\.js\fR
.
.IP "" 4
.
.nf
var EventEmitter = require(\'events\')\.EventEmitter;
module\.exports = new EventEmitter();
// Do some work, and after some time emit
// the \'ready\' event from the module itself\.
setTimeout(function() {
  module\.exports\.emit(\'ready\');
}, 1000);
.
.fi
.
.IP "" 0
.
.P
Then in another file we could do
.
.IP "" 4
.
.nf
var a = require(\'\./a\');
a\.on(\'ready\', function() {
  console\.log(\'module a is ready\');
});
.
.fi
.
.IP "" 0
.
.P
Note that assignment to \fBmodule\.exports\fR must be done immediately\. It cannot be
done in any callbacks\.  This does not work:
.
.P
x\.js:
.
.IP "" 4
.
.nf
setTimeout(function() {
  module\.exports = { a: "hello" };
}, 0);
.
.fi
.
.IP "" 0
.
.P
y\.js:
.
.IP "" 4
.
.nf
var x = require(\'\./x\');
console\.log(x\.a);
.
.fi
.
.IP "" 0
.
.SS "module\.require"
The \fBmodule\.require\fR method provides a way to load a module as if \fBrequire()\fR was called from the original module\.
.
.P
Note that in order to do this, you must get a reference to the \fBmodule\fR
object\.  Since \fBrequire()\fR returns the \fBexports\fR, and the \fBmodule\fR is
typically \fIonly\fR available within a specific module\'s code, it must be
explicitly exported in order to be used\.
.
.SS "All Together\.\.\."
To get the exact filename that will be loaded when \fBrequire()\fR is called, use
the \fBrequire\.resolve()\fR function\.
.
.P
Putting together all of the above, here is the high\-level algorithm
in pseudocode of what require\.resolve does:
.
.IP "" 4
.
.nf
require(X) from module at path Y
1\. If X is a core module,
   a\. return the core module
   b\. STOP
2\. If X begins with \'\./\' or \'/\' or \'\.\./\'
   a\. LOAD_AS_FILE(Y + X)
   b\. LOAD_AS_DIRECTORY(Y + X)
3\. LOAD_NODE_MODULES(X, dirname(Y))
4\. THROW "not found"
LOAD_AS_FILE(X)
1\. If X is a file, load X as JavaScript text\.  STOP
2\. If X\.js is a file, load X\.js as JavaScript text\.  STOP
3\. If X\.node is a file, load X\.node as binary addon\.  STOP
LOAD_AS_DIRECTORY(X)
1\. If X/package\.json is a file,
   a\. Parse X/package\.json, and look for "main" field\.
   b\. let M = X + (json main field)
   c\. LOAD_AS_FILE(M)
2\. LOAD_AS_FILE(X/index)
LOAD_NODE_MODULES(X, START)
1\. let DIRS=NODE_MODULES_PATHS(START)
2\. for each DIR in DIRS:
   a\. LOAD_AS_FILE(DIR/X)
   b\. LOAD_AS_DIRECTORY(DIR/X)
NODE_MODULES_PATHS(START)
1\. let PARTS = path split(START)
2\. let ROOT = index of first instance of "node_modules" in PARTS, or 0
3\. let I = count of PARTS \- 1
4\. let DIRS = []
5\. while I > ROOT,
   a\. if PARTS[I] = "node_modules" CONTINUE
   c\. DIR = path join(PARTS[0 \.\. I] + "node_modules")
   b\. DIRS = DIRS + DIR
   c\. let I = I \- 1
6\. return DIRS
.
.fi
.
.IP "" 0
.
.SS "Loading from the global folders"
If the \fBNODE_PATH\fR environment variable is set to a colon\-delimited list
of absolute paths, then node will search those paths for modules if they
are not found elsewhere\.  (Note: On Windows, \fBNODE_PATH\fR is delimited by
semicolons instead of colons\.)
.
.P
Additionally, node will search in the following locations:
.
.IP "\(bu" 4
1: \fB$HOME/\.node_modules\fR
.
.IP "\(bu" 4
2: \fB$HOME/\.node_libraries\fR
.
.IP "\(bu" 4
3: \fB$PREFIX/lib/node\fR
.
.IP "" 0
.
.P
Where \fB$HOME\fR is the user\'s home directory, and \fB$PREFIX\fR is node\'s
configured \fBinstallPrefix\fR\|\.
.
.P
These are mostly for historic reasons\.  You are highly encouraged to
place your dependencies localy in \fBnode_modules\fR folders\.  They will be
loaded faster, and more reliably\.
.
.SS "Accessing the main module"
When a file is run directly from Node, \fBrequire\.main\fR is set to its \fBmodule\fR\|\. That means that you can determine whether a file has been run
directly by testing
.
.IP "" 4
.
.nf
require\.main === module
.
.fi
.
.IP "" 0
.
.P
For a file \fBfoo\.js\fR, this will be \fBtrue\fR if run via \fBnode foo\.js\fR, but \fBfalse\fR if run by \fBrequire(\'\./foo\')\fR\|\.
.
.P
Because \fBmodule\fR provides a \fBfilename\fR property (normally equivalent to \fB__filename\fR), the entry point of the current application can be obtained
by checking \fBrequire\.main\.filename\fR\|\.
.
.SH "Addenda: Package Manager Tips"
The semantics of Node\'s \fBrequire()\fR function were designed to be general
enough to support a number of sane directory structures\. Package manager
programs such as \fBdpkg\fR, \fBrpm\fR, and \fBnpm\fR will hopefully find it possible to
build native packages from Node modules without modification\.
.
.P
Below we give a suggested directory structure that could work:
.
.P
Let\'s say that we wanted to have the folder at \fB/usr/lib/node/<some\-package>/<some\-version>\fR hold the contents of a
specific version of a package\.
.
.P
Packages can depend on one another\. In order to install package \fBfoo\fR, you
may have to install a specific version of package \fBbar\fR\|\.  The \fBbar\fR package
may itself have dependencies, and in some cases, these dependencies may even
collide or form cycles\.
.
.P
Since Node looks up the \fBrealpath\fR of any modules it loads (that is,
resolves symlinks), and then looks for their dependencies in the \fBnode_modules\fR folders as described above, this situation is very simple to
resolve with the following architecture:
.
.IP "\(bu" 4
\fB/usr/lib/node/foo/1\.2\.3/\fR \- Contents of the \fBfoo\fR package, version 1\.2\.3\.
.
.IP "\(bu" 4
\fB/usr/lib/node/bar/4\.3\.2/\fR \- Contents of the \fBbar\fR package that \fBfoo\fR
depends on\.
.
.IP "\(bu" 4
\fB/usr/lib/node/foo/1\.2\.3/node_modules/bar\fR \- Symbolic link to \fB/usr/lib/node/bar/4\.3\.2/\fR\|\.
.
.IP "\(bu" 4
\fB/usr/lib/node/bar/4\.3\.2/node_modules/*\fR \- Symbolic links to the packages
that \fBbar\fR depends on\.
.
.IP "" 0
.
.P
Thus, even if a cycle is encountered, or if there are dependency
conflicts, every module will be able to get a version of its dependency
that it can use\.
.
.P
When the code in the \fBfoo\fR package does \fBrequire(\'bar\')\fR, it will get the
version that is symlinked into \fB/usr/lib/node/foo/1\.2\.3/node_modules/bar\fR\|\.
Then, when the code in the \fBbar\fR package calls \fBrequire(\'quux\')\fR, it\'ll get
the version that is symlinked into \fB/usr/lib/node/bar/4\.3\.2/node_modules/quux\fR\|\.
.
.P
Furthermore, to make the module lookup process even more optimal, rather
than putting packages directly in \fB/usr/lib/node\fR, we could put them in \fB/usr/lib/node_modules/<name>/<version>\fR\|\.  Then node will not bother
looking for missing dependencies in \fB/usr/node_modules\fR or \fB/node_modules\fR\|\.
.
.P
In order to make modules available to the node REPL, it might be useful to
also add the \fB/usr/lib/node_modules\fR folder to the \fB$NODE_PATH\fR environment
variable\.  Since the module lookups using \fBnode_modules\fR folders are all
relative, and based on the real path of the files making the calls to \fBrequire()\fR, the packages themselves can be anywhere\.