.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODE\-STREAMS" "3" "October 2011" "" ""
.
.SH "NAME"
\fBnode-streams\fR \-\- http://nodejs\.org/docs/v0\.4\.8/api/streams\.html
.
.SH "Streams"
A stream is an abstract interface implemented by various objects in Node\.
For example a request to an HTTP server is a stream, as is stdout\. Streams
are readable, writable, or both\. All streams are instances of \fBEventEmitter\fR\|\.
.
.SH "Readable Stream"
A \fBReadable Stream\fR has the following methods, members, and events\.
.
.SS "Event: \'data\'"
\fBfunction (data) { }\fR
.
.P
The \fB\'data\'\fR event emits either a \fBBuffer\fR (by default) or a string if \fBsetEncoding()\fR was used\.
.
.SS "Event: \'end\'"
\fBfunction () { }\fR
.
.P
Emitted when the stream has received an EOF (FIN in TCP terminology)\.
Indicates that no more \fB\'data\'\fR events will happen\. If the stream is also
writable, it may be possible to continue writing\.
.
.SS "Event: \'error\'"
\fBfunction (exception) { }\fR
.
.P
Emitted if there was an error receiving data\.
.
.SS "Event: \'close\'"
\fBfunction () { }\fR
.
.P
Emitted when the underlying file descriptor has been closed\. Not all streams
will emit this\.  (For example, an incoming HTTP request will not emit \fB\'close\'\fR\|\.)
.
.SS "Event: \'fd\'"
\fBfunction (fd) { }\fR
.
.P
Emitted when a file descriptor is received on the stream\. Only UNIX streams
support this functionality; all others will simply never emit this event\.
.
.SS "stream\.readable"
A boolean that is \fBtrue\fR by default, but turns \fBfalse\fR after an \fB\'error\'\fR
occurred, the stream came to an \fB\'end\'\fR, or \fBdestroy()\fR was called\.
.
.SS "stream\.setEncoding(encoding)"
Makes the data event emit a string instead of a \fBBuffer\fR\|\. \fBencoding\fR can be \fB\'utf8\'\fR, \fB\'ascii\'\fR, or \fB\'base64\'\fR\|\.
.
.SS "stream\.pause()"
Pauses the incoming \fB\'data\'\fR events\.
.
.SS "stream\.resume()"
Resumes the incoming \fB\'data\'\fR events after a \fBpause()\fR\|\.
.
.SS "stream\.destroy()"
Closes the underlying file descriptor\. Stream will not emit any more events\.
.
.SS "stream\.destroySoon()"
After the write queue is drained, close the file descriptor\.
.
.SS "stream\.pipe(destination, [options])"
This is a \fBStream\.prototype\fR method available on all \fBStream\fRs\.
.
.P
Connects this read stream to \fBdestination\fR WriteStream\. Incoming
data on this stream gets written to \fBdestination\fR\|\. The destination and source
streams are kept in sync by pausing and resuming as necessary\.
.
.P
This function returns the \fBdestination\fR stream\.
.
.P
Emulating the Unix \fBcat\fR command:
.
.IP "" 4
.
.nf
process\.stdin\.resume();
process\.stdin\.pipe(process\.stdout);
.
.fi
.
.IP "" 0
.
.P
By default \fBend()\fR is called on the destination when the source stream emits \fBend\fR, so that \fBdestination\fR is no longer writable\. Pass \fB{ end: false }\fR as \fBoptions\fR to keep the destination stream open\.
.
.P
This keeps \fBprocess\.stdout\fR open so that "Goodbye" can be written at the end\.
.
.IP "" 4
.
.nf
process\.stdin\.resume();
process\.stdin\.pipe(process\.stdout, { end: false });
process\.stdin\.on("end", function() {
  process\.stdout\.write("Goodbye\\n");
});
.
.fi
.
.IP "" 0
.
.P
NOTE: If the source stream does not support \fBpause()\fR and \fBresume()\fR, this function
adds simple definitions which simply emit \fB\'pause\'\fR and \fB\'resume\'\fR events on
the source stream\.
.
.SH "Writable Stream"
A \fBWritable Stream\fR has the following methods, members, and events\.
.
.SS "Event: \'drain\'"
\fBfunction () { }\fR
.
.P
Emitted after a \fBwrite()\fR method was called that returned \fBfalse\fR to
indicate that it is safe to write again\.
.
.SS "Event: \'error\'"
\fBfunction (exception) { }\fR
.
.P
Emitted on error with the exception \fBexception\fR\|\.
.
.SS "Event: \'close\'"
\fBfunction () { }\fR
.
.P
Emitted when the underlying file descriptor has been closed\.
.
.SS "Event: \'pipe\'"
\fBfunction (src) { }\fR
.
.P
Emitted when the stream is passed to a readable stream\'s pipe method\.
.
.SS "stream\.writable"
A boolean that is \fBtrue\fR by default, but turns \fBfalse\fR after an \fB\'error\'\fR
occurred or \fBend()\fR / \fBdestroy()\fR was called\.
.
.SS "stream\.write(string, encoding=\'utf8\', [fd])"
Writes \fBstring\fR with the given \fBencoding\fR to the stream\.  Returns \fBtrue\fR if
the string has been flushed to the kernel buffer\.  Returns \fBfalse\fR to
indicate that the kernel buffer is full, and the data will be sent out in
the future\. The \fB\'drain\'\fR event will indicate when the kernel buffer is
empty again\. The \fBencoding\fR defaults to \fB\'utf8\'\fR\|\.
.
.P
If the optional \fBfd\fR parameter is specified, it is interpreted as an integral
file descriptor to be sent over the stream\. This is only supported for UNIX
streams, and is silently ignored otherwise\. When writing a file descriptor in
this manner, closing the descriptor before the stream drains risks sending an
invalid (closed) FD\.
.
.SS "stream\.write(buffer)"
Same as the above except with a raw buffer\.
.
.SS "stream\.end()"
Terminates the stream with EOF or FIN\.
.
.SS "stream\.end(string, encoding)"
Sends \fBstring\fR with the given \fBencoding\fR and terminates the stream with EOF
or FIN\. This is useful to reduce the number of packets sent\.
.
.SS "stream\.end(buffer)"
Same as above but with a \fBbuffer\fR\|\.
.
.SS "stream\.destroy()"
Closes the underlying file descriptor\. Stream will not emit any more events\.
.
.SS "stream\.destroySoon()"
After the write queue is drained, close the file descriptor\. \fBdestroySoon()\fR
can still destroy straight away, as long as there is no data left in the queue
for writes\.