.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODE\-APPENDIX_1" "3" "October 2011" "" ""
.
.SH "NAME"
\fBnode-appendix_1\fR \-\- http://nodejs\.org/docs/v0\.4\.8/api/appendix_1\.html
.
.SH "Appendix 1 \- Third Party Modules"
There are many third party modules for Node\. At the time of writing, August
2010, the master repository of modules is the wiki page \fIhttp://github\.com/joyent/node/wiki/modules\fR\|\.
.
.P
This appendix is intended as a SMALL guide to new\-comers to help them
quickly find what are considered to be quality modules\. It is not intended
to be a complete list\.  There may be better more complete modules found
elsewhere\.
.
.IP "\(bu" 4
Module Installer: npm \fIhttp://github\.com/isaacs/npm\fR
.
.IP "\(bu" 4
HTTP Middleware: Connect \fIhttp://github\.com/senchalabs/connect\fR
.
.IP "\(bu" 4
Web Framework: Express \fIhttp://github\.com/visionmedia/express\fR
.
.IP "\(bu" 4
Web Sockets: Socket\.IO \fIhttp://github\.com/LearnBoost/Socket\.IO\-node\fR
.
.IP "\(bu" 4
HTML Parsing: HTML5 \fIhttp://github\.com/aredridel/html5\fR
.
.IP "\(bu" 4
mDNS/Zeroconf/Bonjour \fIhttp://github\.com/agnat/node_mdns\fR
.
.IP "\(bu" 4
RabbitMQ, AMQP \fIhttps://github\.com/postwait/node\-amqp\fR
.
.IP "\(bu" 4
mysql \fIhttp://github\.com/felixge/node\-mysql\fR
.
.IP "\(bu" 4
Serialization: msgpack \fIhttp://github\.com/pgriess/node\-msgpack\fR
.
.IP "\(bu" 4
Scraping: Apricot \fIhttp://github\.com/silentrob/Apricot\fR
.
.IP "\(bu" 4
Debugger: ndb \fIhttp://github\.com/smtlaissezfaire/ndb\fR is a CLI debugger inspector \fIhttp://github\.com/dannycoates/node\-inspector\fR is a web based
tool\.
.
.IP "\(bu" 4
pcap binding \fIhttp://github\.com/mranney/node_pcap\fR
.
.IP "\(bu" 4
ncurses \fIhttp://github\.com/mscdex/node\-ncurses\fR
.
.IP "\(bu" 4
Testing/TDD/BDD: vows \fIhttp://vowsjs\.org/\fR, expresso \fIhttp://github\.com/visionmedia/expresso\fR, mjsunit\.runner \fIhttp://github\.com/tmpvar/mjsunit\.runner\fR
.
.IP "" 0
.
.P
Patches to this list are welcome\.