.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODE\-SYNOPSIS" "3" "October 2011" "" ""
.
.SH "NAME"
\fBnode-synopsis\fR \-\- http://nodejs\.org/docs/v0\.4\.8/api/synopsis\.html
.
.SH "Synopsis"
An example of a web server \fIhttp\.html\fR written with Node which responds with \'Hello
World\':
.
.IP "" 4
.
.nf
var http = require(\'http\');
http\.createServer(function (request, response) {
  response\.writeHead(200, {\'Content\-Type\': \'text/plain\'});
  response\.end(\'Hello World\\n\');
})\.listen(8124);
console\.log(\'Server running at http://127\.0\.0\.1:8124/\');
.
.fi
.
.IP "" 0
.
.P
To run the server, put the code into a file called \fBexample\.js\fR and execute
it with the node program
.
.IP "" 4
.
.nf
> node example\.js
Server running at http://127\.0\.0\.1:8124/
.
.fi
.
.IP "" 0
.
.P
All of the examples in the documentation can be run similarly\.