.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODE\-URL" "3" "October 2011" "" ""
.
.SH "NAME"
\fBnode-url\fR \-\- http://nodejs\.org/docs/v0\.4\.8/api/url\.html
.
.SH "URL"
This module has utilities for URL resolution and parsing\.
Call \fBrequire(\'url\')\fR to use it\.
.
.P
Parsed URL objects have some or all of the following fields, depending on
whether or not they exist in the URL string\. Any parts that are not in the URL
string will not be in the parsed object\. Examples are shown for the URL
.
.P
\fB\'http://user:pass@host\.com:8080/p/a/t/h?query=string#hash\'\fR
.
.IP "\(bu" 4
\fBhref\fR: The full URL that was originally parsed\. Both the protocol and host are lowercased\.
.
.IP
Example: \fB\'http://user:pass@host\.com:8080/p/a/t/h?query=string#hash\'\fR
.
.IP "\(bu" 4
\fBprotocol\fR: The request protocol, lowercased\.
.
.IP
Example: \fB\'http:\'\fR
.
.IP "\(bu" 4
\fBhost\fR: The full lowercased host portion of the URL, including port and authentication information\.
.
.IP
Example: \fB\'user:pass@host\.com:8080\'\fR
.
.IP "\(bu" 4
\fBauth\fR: The authentication information portion of a URL\.
.
.IP
Example: \fB\'user:pass\'\fR
.
.IP "\(bu" 4
\fBhostname\fR: Just the lowercased hostname portion of the host\.
.
.IP
Example: \fB\'host\.com\'\fR
.
.IP "\(bu" 4
\fBport\fR: The port number portion of the host\.
.
.IP
Example: \fB\'8080\'\fR
.
.IP "\(bu" 4
\fBpathname\fR: The path section of the URL, that comes after the host and before the query, including the initial slash if present\.
.
.IP
Example: \fB\'/p/a/t/h\'\fR
.
.IP "\(bu" 4
\fBsearch\fR: The \'query string\' portion of the URL, including the leading question mark\.
.
.IP
Example: \fB\'?query=string\'\fR
.
.IP "\(bu" 4
\fBquery\fR: Either the \'params\' portion of the query string, or a querystring\-parsed object\.
.
.IP
Example: \fB\'query=string\'\fR or \fB{\'query\':\'string\'}\fR
.
.IP "\(bu" 4
\fBhash\fR: The \'fragment\' portion of the URL including the pound\-sign\.
.
.IP
Example: \fB\'#hash\'\fR
.
.IP "" 0
.
.P
The following methods are provided by the URL module:
.
.SS "url\.parse(urlStr, parseQueryString=false)"
Take a URL string, and return an object\.  Pass \fBtrue\fR as the second argument to also parse
the query string using the \fBquerystring\fR module\.
.
.SS "url\.format(urlObj)"
Take a parsed URL object, and return a formatted URL string\.
.
.SS "url\.resolve(from, to)"
Take a base URL, and a href URL, and resolve them as a browser would for an anchor tag\.